apiVersion: v1
kind: Pod
metadata:
  name: notebook
  label:
    app:jupyter-notebook
spec:
  containers:
    name: notebook
    image: 40660367/myub18_notebook
    command: ['jupyter']
    args: ['notebook','--allow-root','--ip=0.0.0.0']
